---
title: "Introduction to Hypothesis Testing"
date: "March 25, 2024"
output:
  xaringan::moon_reader:
    css: "myCSS.css"
    self_contained: true
    chakra: "remark-latest.min.js"
    nature:
      countIncrementalSlides: false
---

### Basic Principles of Hypothesis Testing

--

A statistical hypothesis is often a statement about one or more population parameters.

--

- The **null hypothesis** *(denoted by Ho)* about a parameter states that the parameter is **equal** to a specific value, for example, Ho: $\mu$ = 35.

--

- The **alternate hypothesis** *(denoted by $H_1$)* about a parameter states that the value of the parameter **differs** from the value specified by the null hypothesis.

--

The magazine Tech Worx reported that 92% of software engineers rate the company they work for as "a great place to work." As a veteran headhunter, you claim the percentage given in the report is not correct. In a survey of 210 randomly chosen software engineers, 188 rated the company they work for as "a great place to work."

Perform a hypothesis test to see if there is enough evidence, at the 0.10 level of significance, to support your claim that the proportion, p, of all software engineers who rate the company they work for as "a great place to work" is not 92%.

---

There are three types of alternate hypothesis:

--

- A **left-tailed** alternate hypothesis states that the parameter is *less than* the value specified by the null hypothesis, for example, $H_1: \mu < 35$

--

- A **right-tailed** alternate hypothesis states that the parameter is *greater than* the value specified by the null hypothesis, for example, $H_1: \mu > 35$

--

- A **two-tailed** alternate hypothesis states that the parameter is *not equal* to the value specified by the null hypothesis, for example, $H_1: \mu \neq 35$

--

The left-tailed and right-tailed hypotheses are called **one-tailed** hypothesis.


--

We begin a hypothesis test by assuming the null hypothesis is **true**.

--

If the data provide strong evidence against the null hypothesis, we reject it, and believe the alternate hypothesis.

--

If there is not sufficient evidence to reject the null hypothesis, we conclude that the null hypothesis "might" be true, but we never conclude that the null hypothesis is true.


---


### Errors in Hypothesis Testing (Type I and II)

--

Decision | Ho is true | Ho is false
-----|-----|-----
Reject Ho | Type I error | Correct
Don't reject Ho | Correct | Type II error 

--

**Type I error:** The error of rejecting Ho when Ho is true.

--

- The probability of Type I error is denoted by $\alpha$, the **significance level** of the test.

--

- $\alpha$ = P(Reject Ho | Ho is true)

--

**Type II error:** The error of failing to reject Ho when Ho is false

--

- The probability of a Type II error is denoted by $\beta$

--

The **Power of the test** is the probability of rejecting Ho when Ho is false.

--

- Power = 1 - $\beta$


---

### A hypothesis test is like a trial

--

In criminal trials in the United States, the jury is always told that the defendant is “innocent until proven guilty” *(Claim)*.

--

*1)*  What must a member of the jury assume about the defendant at the beginning of the trial?  This is the null hypothesis.

--

- Ho: Defendant is innocent

--

*2)* It is the prosecuting attorney’s job to present evidence to the jury.  IF there is enough evidence (“beyond a reasonable doubt”), then the jury will convict the defendant of the crime.   If the defendant is convicted, the jury is rejecting the null hypothesis (above) and saying the the defendant is .......

--

- $H_1$: Defendant is guilty


---

*3)* When the jury convicts someone of a crime, their verdict is GUILTY. Is this “Reject Ho”  OR “Fail to Reject Ho”? 

--

- Reject Ho


--

*4)* If the jury fails to convict someone of a crime, their verdict is NOT GUILTY. Is this “Reject Ho”  OR “Fail to Reject Ho”?

--

- Fail to reject Ho

--

*4a)* How does the verdict of “not guilty” differ from “innocent”?

--

- “Not Guilty” indicates that there was not enough evidence to convict the defendant.  This verdict makes no statement about whether or not the defendant committed the crime.

--

- “Innocent” indicates that the defendant did not commit the crime.


---

*5)*  Sometimes the jury makes a correct decision and sometime the jury makes a mistake.

--

*5a)*  When Ho is true, but we reject it based on the sample evidence, this is an error.  We call it a Type I error.   Write a sentence describing a Type I error in the U.S. criminal justice system.

--

- Type I Error = Guilty Verdict When Defendant Is Innocent

--

*5b)*  When Ho is false, but we fail to reject it based on the sample evidence, this is also an error.  We call it a Type II error.  Write a sentence describing a Type II error in the U.S. criminal justice system.

--

- Type II Error = NOT Guilty Verdict When Defendant is Guilty


---


**Medical Testing**

Medical tests have been developed to detect many serious diseases (such as cancer and HIV).  A medical test is designed to give correct results as often as possible.  That is, to minimize the occurrence of “false positives” and “false negatives”.

A doctor starts by assuming that a patient is healthy (no disease), then looks for evidence to contradict that assumption.  If the patient has a negative test result, the doctor continues to assume that the patient is healthy.  If the patient has a positive test result, the doctor concludes that the patient has a disease.

*a)*  State Ho and $H_1$.

--

- Ho: Patient Is Healthy   $H_1$: Patient Has Disease

--

*b)*  When will the doctor Reject Ho?

--

- Doctor rejects Ho when test result is positive.


---

*c)*  When will the doctor Fail to Reject Ho?

--

- Doctor fails to reject Ho when test result is negative.

--

*d)*  What kind of an error is a “false positive”?  EXPLAIN.

--

- A false positive is a Type I error (reject Ho when Ho is true).

--

*e)*  What kind of an error is a “false negative”?  EXPLAIN.

--

- A false negative is a Type II error (fail to reject Ho when Ho is false).

--

*f)*  What are the consequences of a false positive?  Of a false negative?

--

- With a false positive, a person thinks they have a disease (and may start treatment) when they are healthy.  With a false negative, a person doesn’t know they have a disease (and don’t start treatment).


---



---


### The P-Value

--

- The **P-value** is the probability that chance alone would produce a test statistic as extreme as the observed test statistic. 

--

- Assuming that the null hypothesis is true, we must first decide which values of the test statistic are at least as contradictory to Ho as the value obtained from our sample.

--

- Reject Ho if P-value $\leq$ $\alpha$

--

- Fail to reject Ho if P-value > $\alpha$




