---
title: "Review for Exam 1"
date: "February 10, 2025"
output:
  xaringan::moon_reader:
    css: "myCSS.css"
    chakra: "remark-latest.min.js"
    self_contained: true
    nature:
      countIncrementalSlides: false
---


### Basic Definitions

--

**Population**

--

- *(Textbook)* A **population** is the entire collection of individuals about which information is sought.

--

- All possible outcomes in a chance experiment.

--

**Sample**

--

- *(Textbook)* A **sample** is a subset of a population, containing the individuals that are actually observed.

--

- A **simple random sample** of size *n* is a sample chosen by a method in which each collection of *n* population items is equally likely to make up the sample, just as in lottery.



---

### Understanding Measures of Center or Typical Value (Mean vs Median)

--

**Sample Mean:** It is denoted with the symbol $\bar{X}$. 

--

- Computation: Add all values $(\sum x_i)$ and divided by the sample size (n).


--

- Formula: $\bar{X} = \frac{1}{n}\sum x_i$

--

- The "average" or typical value of your data is measured by the **mean**. The population mean is denoted with the symbol $\mu$  (read as mu). The sample mean is denoted with the symbol $\bar{X}$ (read as X-BAR).

--


**Median:** By definition, it is a number that splits the data set in half. 

--

- Step 1: Sort the data in ascending order. 

--

- Step 2: If the sample size is ODD, the median is the number in the middle position, else the median is the average of the two middle numbers.


---

**Flight Time**: The following data represent the flight time (in minutes) of a random sample of seven flights from Las Vegas, Nevada, to Newark, New Jersey, on United Airlines: 282, 270, 260, 266, 257, 260, 277.

--

Sample Mean: $\bar{X} = \frac{1}{n}\sum X_i$

--

-  $\bar{X} = \frac{1}{7}(282 + 270 + 260 + 266 + 257 + 260 + 277)$


--

- $\bar{X} = \frac{1}{7}(1872)$ = 267.43

--

Median = 266

--

- Sort data: 257 260 260 266 270 277 282

--

- Since the sample size is odd, 7, Median is the number in $4^{th}$ position, 266


---



### Mean vs Median vs Mode

Shape | Relationship | Best Summary of Center
----|----|----
Bell-Shaped | mean = median = mode | mean
Skewed Right | mean > median > mode | median
Skewed Left | mean < median < mode | median 

--

- The **mode** of a variable is the **most frequent** observation in the data set.

--

- Be careful, the mode is not a measure of central tendency!!!

--

- The mean (or median) can be interpreted as "typical values" or "averages". We can also say that half of the data is below (or above) the median.

--

- The best summary (mean or median) of the center depends on the "shape" of the variable's distribution.


---

### Approximating the Mean with Grouped Data


The table below presents the number of text messages sent by a sample of 50 high school students. We will **approximate** the mean number of messages sent.

Messages sent | Frequency
-----|----
0 - 49 | 10
50 - 99 | 5
100 - 149 | 13
150 - 199 | 11
200 - 249 | 7
250 - 299 | 4

---

```{r comment=NA, echo=FALSE, message=FALSE, fig.align='center'}

library(tidyverse)

ggplot(data=NULL) +
  aes(x=c(0,50,100,150,200,250),y=c(10,5,13,11,7,4)) +
  geom_col(position = "dodge", width = 50, fill = "white", col = "black", just = 0) +
  scale_x_continuous(breaks = c(0,50,100,150,200,250,300)) +
  labs(x = "\nNumber of Text Messages Sent", y="Frequency\n", title="Frequency Histogram of Number of Text Messages Sent")


```

---

#### Procedures for Approximating the Mean with Grouped Data

--

Step 1: Compute the midpoint of each class.

--

- The midpoint of a class if found by taking the average of the lower class limit and the lower limit of the next larger class. For the last class, there is no next larger class, but we use the lower limit that the next larger class would have.

--

Messages sent | Frequency | Midpoint
-----|----|----
0 - 49 | 10 | 25
50 - 99 | 5 | 75
100 - 149 | 13 | 125
150 - 199 | 11 | 175
200 - 249 | 7 | 225
250 - 299 | 4 | 275

---

Step 2: For each class, multiply the class midpoint by the class frequency.

--

Messages sent | Frequency | Midpoint | F x M
-----|----|----|----
0 - 49 | 10 | 25 | 250
50 - 99 | 5 | 75 | 375
100 - 149 | 13 | 125 | 1625
150 - 199 | 11 | 175 | 1925
200 - 249 | 7 | 225 | 1575
250 - 299 | 4 | 275 | 1100

--

Step 3: Add the products (Midpoint x Frequency) over all classes.

--

- Total of (F x M) = 250 + 375 + 1625 + 1925 + 1575 + 1100 = **6850**

--

Step 4: Divide the sum obtained in Step 3 by the sum of the frequencies.

--

- Mean $\approx$ 6850 / 50 = **137**


---

### The Weighted Mean

--

*Definition:* If $x_1, x_2, ...x_n$ are data values, and $w_1, w_2, ..., w_n$ are weights, the **weighted mean** is

- $\bar{X}_w = \frac{w_1x_1 + w_2x_2 + ... + w_nx_n}{w_1 + w_2 + ... + w_n} = \frac{w_ix_i}{w_i}$

--

Last semester Joe took four courses. He got A is statistics (5 credits), a B in psychology (4 credits), a C in English (3 credits), and an A in music (2 credits). An A is worth 4 quality points, a B is worth 3 points and a C is worth 2 points. Compute Joe's GPA.

--

- The data values are the points for each grade: 4, 3, 2, and 4.

--

- The weights are the number of credits: 5, 4, 3, 2.

--

- The GPA is the weighted mean: $\frac{5(4) + 4(3) + 3(2) + 2(4)}{5 + 4 + 3 + 2}$ 
--

- GPA = **3.29**

---


### Variability or Spread for NUMERICAL data

--

**Range:** It is the difference between the maximum and the minimum values in your data.

--

- Formula: Max - Min

--

The **sample variance:** It is denoted with the symbol $S^2$.

--

- Formula: $S^2 = \frac{1}{n - 1}\sum(x_i - \bar{X})^2$

--

The **sample standard deviation** is the square root of the variance: $S = \sqrt{S^2}$

--

- Interpret the standard deviation as the average distance of all data values to the mean.

--

If the population is known, the population variance computed with the formula  $\sigma^2 = \frac{1}{n}\sum(x_i - \mu)^2$. 

- The population standard deviation is $\sigma$ *(read as sigma)*.



---

**Flight Time**: The following data represent the flight time (in minutes) of a random sample of seven flights from Las Vegas, Nevada, to Newark, New Jersey, on United Airlines:

282, 270, 260, 266, 257, 260, 267

Compute the spread (or variability) of flight time data. 

--

- It is possible to measure the "spread" of your data with the **range, standard deviation and IQR**.

--

- By definition, the **range** is the difference between the maximum and minimum data values. 

--

- In this example, **Range** = 282 - 257 = 25 minutes.

---

Step 1: Before computing the variance, it is necessary to find the mean, $\bar{X}$.

--

- $\bar{x}$ = $\frac{282 + 270 + 260 + 266 + 257 + 260 + 267}{7}$ = $\frac{1862}{7}$ = 266


--

Step 2: Compute the difference between the data values and the mean.

time | $(x_i - \bar{x})$
----|----
282 | 16
270 | 4
260 | -6
266 | 0
257 | -9
260 | -6
267 | 1

---

Step 3: Square the differences obtained in column 2

time | $(x_i - \bar{x})$ | $(x_i - \bar{x})^2$
----|----|----
282 | 16 | 256
270 | 4  | 16
260 | -6 | 36
266 | 0  | 0
257 | -9 | 81
260 | -6 | 36
267 | 1  | 1


---

Step 4: Add the total in column 3

time | $(x_i - \bar{x})$ | $(x_i - \bar{x})^2$
----|----|----
282 | 16 | 256
270 | 4  | 16
260 | -6 | 36
266 | 0  | 0
257 | -9 | 81
260 | -6 | 36
267 | 1  | 1
**Total** | . | **426**

---

Step 5: Get the variance by dividing the total by (n-1) where n is the sample size.

time | $(x_i - \bar{x})$ | $(x_i - \bar{x})^2$
----|----|----
282 | 16 | 256
270 | 4  | 16
260 | -6 | 36
266 | 0  | 0
257 | -9 | 81
260 | -6 | 36
267 | 1  | 1
**Total** | . | **426** 

--

- Variance, $S^2$ = $\frac{426}{6}$ = 71 mins $^2$

--

- Standard Deviation, S = $\sqrt{S^2}$ = $\sqrt{71}$ = 8.426 mins


---

### Computing the Standard Deviation for Grouped Data.

Messages sent | Frequency
-----|----
0 - 49 | 10
50 - 99 | 5
100 - 149 | 13
150 - 199 | 11
200 - 249 | 7
250 - 299 | 4

--

Find the midpoint of each class and compute the grouped mean like we demonstrated previously.

- Grouped mean = 137

---

Messages sent | Frequency | Midpoint | Mean
-----|----|----|----
0 - 49 | 10 | 25 | 137
50 - 99 | 5 | 75 | 137
100 - 149 | 13 | 125 | 137
150 - 199 | 11 | 175 | 137
200 - 249 | 7 | 225 | 137
250 - 299 | 4 | 275 | 137

--

Compute (midpoint - Mean)

---

Messages sent | Frequency | Midpoint | Mean | Md - Mn |
-----|----|----|----|----
0 - 49 | 10 | 25 | 137 | -112
50 - 99 | 5 | 75 | 137 | -62
100 - 149 | 13 | 125 | 137 | -12
150 - 199 | 11 | 175 | 137 | 38
200 - 249 | 7 | 225 | 137 | 88
250 - 299 | 4 | 275 | 137 | 138

*(Md = Midpoint, Mn = Mean)*

--

Compute $(Md - Mn)^2$ x Frequency

---

Messages sent | Frequency | Midpoint | Mean | Md - Mn | $(Md - Mn)^2$ x F
-----|----|----|----|----|----
0 - 49 | 10 | 25 | 137 | -112 | 125400
50 - 99 | 5 | 75 | 137 | -62 | 19200
100 - 149 | 13 | 125 | 137 | -12 | 1872
150 - 199 | 11 | 175 | 137 | 38 | 15884
200 - 249 | 7 | 225 | 137 | 88 | 54208
250 - 299 | 4 | 275 | 137 | 138 | 76176

--

- Find the total of $(Md - Mn)^2$ x Frequency, 292800.

--

- Find the total Frequency, 50.

--

- Compute the variance, $S^2 = \frac{292800}{50 - 1}$ = 5975.5102

--

- Compute the Standard Deviation, S = $\sqrt{5975.5102}$ = 77.3014



---

