---
title: "Hypothesis Test for a population Mean: T test"
date: "April 28, 2025"
output:
  xaringan::moon_reader:
    css: "myCSS.css"
    self_contained: true
    chakra: "remark-latest.min.js"
    nature:
      countIncrementalSlides: false
---


### Hypothesis Test For A Population Mean *(when $\sigma$ is unknown)*

--

When $\bar{X}$ is the mean of a sample from a normal population, the quantity

$\frac{\bar{x} - \mu}{S/\sqrt{n}}$

has a Student's t distribution with **n - 1** degrees of freedom.

--

**Assumptions to consider:**

--

- We have a simple random sample

--

- The sample size is large (n > 30), OR the population is approximately normal.


---

### The P-value Method

--

If the assumptions are satisfied, then proceed with the following steps:

--

- STEP 1: State the null and alternate hypotheses. The null hypothesis is of the form Ho: $\mu$ = $\mu_o$ where $\mu_o$ is the hypothesized value of the population mean.

--

- STEP 2: If making a decision, choose a significance level $\alpha$.

--

- STEP 3: Compute the test statistic, t = $\frac{\bar{x} - \mu_o}{S/\sqrt{n}}$

--

- STEP 4: Compute the P-value of the test statistic. Use he ALEKS function P(T $\geq$ t with df = ...). The degrees of freedom are n - 1.

--

- STEP 5: Interpret the P-value. If making a decision, reject Ho if the P-value is less than or equal to the significance level $\alpha$.

--

- STEP 6: State a conclusion.


---

### The Critical Value Method

--

- STEP 1: State the null and alternate hypotheses. The null hypothesis is of the form Ho: $\mu$ = $\mu_o$ where $\mu_o$ is the hypothesized value of the population mean.

--

- STEP 2: Choose a significance level $\alpha$, and find the critical value or values. Use n - 1 degrees of freedom, where n is the sample size.

--

- STEP 3: Compute the test statistic, t = $\frac{\bar{x} - \mu_o}{S/\sqrt{n}}$


--

- STEP 4: Determine whether to reject Ho, as follows. 

- - Left-tailed: $H_1: \mu < \mu_o$, reject if t $\leq -t_{\alpha}$

- - Right-tailed: $H_1: \mu > \mu_o$, reject if t $\geq t_{\alpha}$

- - Two-tailed: $H_1: \mu \neq \mu_o$, reject if t $\leq -t_{\alpha/2}$ or t $\geq t_{\alpha}$

--

- STEP 5: State a conclusion


---


An orange grower is introducing a new variety of orange. The grower claims that the new oranges have a mean pH of 5. To test the claim, an independent researcher chose a random sample of 24 of the new oranges, finding they had a sample mean pH of 4.8 with a sample standard deviation of 0.6. Assume that the population of pH values of the new oranges is approximately normally distributed.

Complete the parts below to perform a hypothesis test to see if there is enough evidence, at the 0.05 level of significance, to reject that $\mu$, the mean pH of the new oranges, is 5.

--

- Ho: $\mu$ = 5

--

- $H_1$: $\mu \neq$ 5

--

- The population standard deviation, $\sigma$, is **UNKNOWN** and the sample size is large (generally n > 30) **OR** the population distribution is at least approximately normal.

--

- T = $\frac{\bar{x} - \mu_0}{\frac{S}{\sqrt{n}}}$

--

- T = $\frac{4.8 - 5}{\frac{0.6}{\sqrt{24}}}$ = -1.633


---

The rejection region approach *(Critical value method)*

--

- Identify $\alpha$ and the type of test.

--

- In ALEKS calculator: $t_{0.025; df=23}$. Use 0.025 because this is a two-tailed test.

--

- The rejection region is: $(-\infty, -2.069)$ and $(2.069, \infty)$

--

- Conclusion: Since the value of the test statistic doesn't lie in the rejection region, the null hypothesis is not rejected. So, there is not enough evidence to reject the claim that the mean pH of the new oranges is 5.

--

The P-Value approach

--

- In ALEKS calculator: 2*P(t > 1.633 with df = 23)

--

- Even though the test statistic T = -1.633, the ALEKS calculator function provides the area for the right tail in this two-tailed test *(multiplication by 2)*. For this reason, you have to use the positive value.

--

- P-value = 0.116. Since P-value > $\alpha$, fail to reject Ho.


---


---


Tardigrades, or water bears, are a type of micro-animal famous for their resilience. In examining the effects of radiation on organisms, an expert claimed that the amount of gamma radiation needed to sterilize a colony of tardigrades no longer has a mean of 1200 Gy (grays). (For comparison, humans cannot withstand more than 10 Gy.) A random sample of 21 tardigrade colonies found that the amount of gamma radiation needed to sterilize a colony had a sample mean of 1165 Gy, with a sample standard deviation of 63 Gy. Assume that the population of amounts of gamma radiation needed to sterilize a colony of tardigrades is approximately normally distributed.

Complete the parts below to perform a hypothesis test to see if there is enough evidence, at the 0.10 level of significance, to support that $\mu$, the mean amount of gamma radiation needed to sterilize a colony of tardigrades, is not equal to 1200 Gy.

--

(a) State the null hypothesis Ho and the alternative hypothesis $H_1$ that you would use for the test.

--

- Ho: $\mu$ = 1200

--

- $H_1: \mu \neq$ 1200

---

(b) Perform a hypothesis test. The test statistic has a t distribution (so the test is a "t test"). Here is some other information to help you with your test.

- $t_{0.05}$ is the value that cuts off an area of 0.05 in the right tail.

- The value of the test statistic is given by $t = \frac{\bar{X} - \mu}{S/\sqrt{n}}$


--


Step 1: Enter the number of degrees of freedom.

--

- df = n - 1 = 21 - 1 = 20

--

Step 2: Select one-tailed or two tailed.

--

- Two-tailed

--

Step 3: Enter the critical value(s). *(Round to 3 decimal places)*

--

- Using ALEKS calculator, compute $t_{0.05; df = 20}$.

--

- $t_{0.05; df = 20}$ = 1.725. The critical values are -1.725 and 1.725


---

Step 4: Enter the test statistic.

--

- $t = \frac{\bar{X} - \mu}{S/\sqrt{n}} = \frac{1165 - 1200}{63/\sqrt{21}}$

--

- t = -2.546

--

(c) Based on your answer to part (b), choose what can be concluded, at the 0.10 level of significance, about the claim made by the expert.

--

- Reject Ho

--

- Since the value of the test statistic lies in the rejection region, the null hypothesis is rejected. So, there is enough evidence to support the claim that the mean amount of gamma radiation needed to sterilize a colony of tardigrades is not equal to 1200 Gy.

---

###  Testing the Population Mean in R Studio


**How much is in that can?** A machine that fills beverage cans is supposed to put 12 ounces of beverage in each can. Following are the amounts measured in a simple random sample of eight cans: 11.96, 12.10, 12.04, 12.13, 11.98, 12.05, 11.91, 12.03. Assuming a normal distribution for the amount of beverage dispensed by the machine, perform a hypothesis test to determine whether the mean volume differs from 12 ounces. Use the $\alpha$ = 0.05 level of significance. What do you conclude?

--

> Step 1: Open R GUI: library(Rcmdr)

> Step 2: Click on Data > New data set > Enter name for data set: **cans** > OK

> Step 3: Click "Add row" fifteen times because there are 8 observations.

> Step 4: Change the columns names from V1 to **ounce**.

> Step 5: Enter the corresponding data *(see above)* like you do in Excel. When you finish, click OK.

---


**Compute the test**

> Step 6: Statistics > Means > Single-sample t-test

> Step 7: Select the variable: dist

> Step 8: Null Hypothesis: mu = 12 > OK

--

```{r comment=NA, echo=F}

# Copy the data values
x <- c(11.96, 12.10, 12.04, 12.13, 11.98, 12.05, 11.91, 12.03)

# Run the hypothesis test, Ho: mu=12, H1: mu != 12
t.test(x, mu = 12)


```

--

**NOTE:** By default, R assumes a two-tailed test (not equal) with alpha 0.05. In addition, recall that alpha is 1 - confidence level. You may need to adjust these parameters according to the conditions in the exercise.



---

- The P-value of 0.3632 is greater than alpha, 0.05.

--

- Therefore, Fail to reject the null hypothesis.

--

- In conclusion, there is not enough evidence to suggest that the mean volume differs from 12 ounces.

--

- In other words, there is not evidence the machine is broken.

