---
title: "Introduction to Hypothesis Testing"
date: "April 3, 2025"
output:
  xaringan::moon_reader:
    css: "myCSS.css"
    self_contained: true
    chakra: "remark-latest.min.js"
    nature:
      countIncrementalSlides: false
---



### Introduction to Hypothesis Testing

--

A statistical hypothesis is often a statement about one or more population parameters.

--

> The **null hypothesis** *(denoted by Ho)* about a parameter states that the parameter is **equal** to a specific value, for example, Ho: $\mu$ = 35.


> The **alternate hypothesis** *(denoted by $H_1$)* about a parameter states that the value of the parameter **differs** from the value specified by the null hypothesis.

--

There are three types of alternate hypothesis:


> A **left-tailed** alternate hypothesis states that the parameter is *less than* the value specified by the null hypothesis, for example, $H_1: \mu < 35$


> A **right-tailed** alternate hypothesis states that the parameter is *greater than* the value specified by the null hypothesis, for example, $H_1: \mu > 35$


> A **two-tailed** alternate hypothesis states that the parameter is *not equal* to the value specified by the null hypothesis, for example, $H_1: \mu \neq 35$


---

The left-tailed and right-tailed hypotheses are called **one-tailed** hypothesis.

--

We begin a hypothesis test by assuming the null hypothesis is **true**.

--


If the data provide strong evidence against the null hypothesis, we reject it, and believe that alternate hypothesis.

--

If there is not sufficient evidence to reject the null hypothesis, we conclude that the null hypothesis "might" be true, but we never conclude that the null hypothesis is true.



---

###  Error Type I and II

--

Decision | Ho is true | Ho is false
:-----|:-----:|:-----:
Reject Ho | Type I error | Correct
Don't reject Ho | Correct | Type II error 

--

**Type I error:** The error of rejecting Ho when Ho is true.


> The probability of Type I error is denoted $\alpha$, the **significance level** of the test.


> $\alpha$ = P(Reject Ho | Ho is true)


--

**Type II error:** The error of failing to reject Ho when Ho is false


> The probability of a Type II error is denoted by $\beta$


--

The **Power of the test** is the probability of rejecting Ho when Ho is false.


> Power = 1 - $\beta$


---

**A hypothesis test is like a trial:** In criminal trials in the United States, the jury is always told that the defendant is “innocent until proven guilty” *(Claim)*.


*1)*  What must a member of the jury assume about the defendant at the beginning of the trial?  This is the null hypothesis.

--

> Ho: Defendant is innocent

--

*2)* It is the prosecuting attorney’s job to present evidence to the jury.  IF there is enough evidence (“beyond a reasonable doubt”), then the jury will convict the defendant of the crime.   If the defendant is convicted, the jury is rejecting the null hypothesis (above) and saying the the defendant is .......

--

> $H_1$: Defendant is guilty

--

*3)* When the jury convicts someone of a crime, their verdict is GUILTY. Is this “Reject Ho”  OR “Fail to Reject Ho”? 

--

> Reject Ho

---


*4)* If the jury fails to convict someone of a crime, their verdict is NOT GUILTY. Is this “Reject Ho”  OR “Fail to Reject Ho”?

--

> Fail to reject Ho

--

*4a)* How does the verdict of “not guilty” differ from “innocent”?

--

> “Not Guilty” indicates that there was not enough evidence to convict the defendant.  This verdict makes no statement about whether or not the defendant committed the crime.

--

> “Innocent” indicates that the defendant did not commit the crime.

--

*5)*  Sometimes the jury makes a correct decision and sometime the jury makes a mistake.


*5a)*  When Ho is true, but we reject it based on the sample evidence, this is an error.  We call it a Type I error.   Write a sentence describing a Type I error in the U.S. criminal justice system.

--

> Type I Error = Guilty Verdict When Defendant Is Innocent

---

*5b)*  When Ho is false, but we fail to reject it based on the sample evidence, this is also an error.  We call it a Type II error.  Write a sentence describing a Type II error in the U.S. criminal justice system.

--

> Type II Error = NOT Guilty Verdict When Defendant is Guilty


---


### The Critical Value Method

--

- The critical value method is based on the idea that we should reject Ho if the value of the test statistic is "unusual" when we assume Ho to be true.

--

- In this method, we choose a **critical value**, which forms a "boundary" between values that are considered unusual and values that are not.

--

- The region that contains the unusual values is called the **critical region**. If the value of the test statistic is **IN** the critical region, we reject Ho.

--

- The critical value we choose depends on how small we believe a probability should be for an event to be considered unusual. In practice, an event with a probability of 0.05 or less is unusual.

--

- The probability that we use to determine whether an event is unusual is called the **significance level**.

--

- If we reject Ho after choosing a significance level $\alpha$, we say the result is **statistically significant** at the $\alpha$ level.


---


### Table of Critical Values *(for a Z test)*

Significance Level $\alpha$: | 0.10 | 0.05 | 0.02 | 0.01
:----|:----:|:----:|:----:|:----:
Left-tailed | -1.282 | -1.645 | -2.054 | -2.326
Right-tailed | 1.282 | 1.645 | 2.054 | 2.326
Two-tailed | $\pm$ 1.645 | $\pm$ 1.96 | $\pm$ 2.326 | $\pm$ 2.576


--

A test is made of Ho: $\mu$ = 1 versus $H_1$: $\mu$ > 1. The value of the test statistic is Z = 1.85.


*a)* Is Ho rejected at the $\alpha$ = 0.05 level?

--

- The alternative hypothesis is $H_1$: $\mu$ > 1, so it is tight-tailed test.

--

- The critical value for $\alpha$=0.05 is $z_{\alpha}$=1.645. For the right-tailed test, we reject Ho if z $\geq$ $z_{\alpha}$. Because 1.85 > 1.645, we reject Ho at the $\alpha$ = 0.05 level.


---

*b)* If Ho rejected at the $\alpha$ = 0.01 level?

--

- The critical value for $\alpha$ = 0.01 is 2.326. 

--

- Since 1.85 < 2.326, we do not reject Ho at the $\alpha$ = 0.01 level.


---

### The P-Value Method

--

Whereas the critical value method tells us only whether the test statistic was unusual or not, the P-value method tells us **exactly** how unusual the test statistic is. For this reason, the P-value method is the more often used in practice.

--

- The P-value is the **probability**, assuming that Ho is true, of observing a value for the test statistic that is as extreme as or more extreme than the value actually observed.


- The smaller the P-value, the stronger the evidence against Ho.

--

**Caution:** The P-value is NOT the probability that the null hypothesis is true.

--

To make a decision whether to reject Ho when using the P-value method:


- If P-value $\leq \alpha$, reject Ho. If P-value > $\alpha$, do not reject Ho.


- If P-value $\leq \alpha$, we say that Ho is rejected at the $\alpha$ level, or that the result is statistically significant at the $\alpha$ level.


---

Which provides stronger evidence against Ho: a P-value of 0.05 or a P-value of 0.50?

--

- <p> The P-value of  0.05 </p>

--

A test is made of Ho: $\mu$ = 30 versus $H_1$: $\mu$ < 30. The test statistic is z = -1.28. Find and interpret the P-value.

--

- Using ALEKS calculator: P(Z $\leq$ -1.28)

--

- The answer is 0.1003

--

- If Ho is true, then the probability of observing a test statistic less than of equal to the value we actually observed *(-1.28)* is 0.1003.

--

- This result is not very unusual, so the evidence against Ho is not strong.


--

**Observation**: Since the alternative in this example is left-tailed, the ALEKS calculator function works well. However, you have to do 1 - P(Z $\leq$ $_$) if the alternative is right-tailed and 2*P(Z $\leq$ -z)* for the two-tailed test.



---

### Hypothesis Test for a Population Proportion: Z Test 

--

**Notation**


- **p** is the population proportion of individuals who are in a specified category.

- $p_o$ is the population proportion specified by Ho.

- **x** is the number of individuals in the sample who are in the specified category.

- **n** is the sample size.

- $\hat{p}$ is the sample proportion of individuals who are in the specified category. $\hat{p}$ = x/n.

--

**Reason for the assumptions**


- The population must be much larger than the sample *(at least 20 times as large)*, so that the sampled items are independent.


- The assumption that both $np_o$ and $n(1 - p_o)$ are at least 10 ensures that the sampling distribution of $\hat{p}$ is approximately normal when we assume that Ho is true.


---

### Assumptions for Performing a Hypothesis Test for a Population Proportion.

--

We can perform a test whenever the sample proportion $\hat{p}$ is approximately normal. This will occur when the following assumptions are met:


- We have a simple random sample.


- The population is at least 20 times as large as the sample.


- The individuals in the population are divided into two categories.


- The values $np_o$ and $n(1 - p_o)$ are both at least 10.


---

### Testing the  Population Proportion Using the P-Value Method.

--

> STEP 1: State the null and alternate hypotheses. The null hypothesis will have the form Ho: p = $p_o$. The alternate hypothesis, $H_1$, will be any of the following: p < $p_o$, p > $p_o$, p $\neq p_o$.


> STEP 2: If making a decision, choose a significance level $\alpha$.


> STEP 3: Compute the test statistic, Z = $\frac{\hat{p} - p_o}{\sqrt{\frac{p_o(1 - p_o)}{n}}}$.


> STEP 4: Compute the P-value. The P-value is the area under the standard normal curve. It depends on the type of test.


> STEP 5: Interpret the P-value. If making a decision, reject Ho if P-value $\leq \alpha$.


> STEP 6: State a conclusion.


---

### Testing the Population Proportion Using the Critical Value Method.

--

> STEP 1: State the null and alternate hypotheses. The null hypothesis is Ho: p = $p_o$. The alternate hypothesis could be any of: p < $p_o$, p > $p_o$, p $\neq p_o$.


> STEP 2: Choose a significance level $\alpha$ and find the critical value or values.


> STEP 3: Compute the test statistic, Z = $\frac{\hat{p} - p_o}{\sqrt{\frac{p_o(1 - p_o)}{n}}}$.


> STEP 4: Determine whether to reject Ho, as follows:

> - Left-tailed test: Reject if z $\leq -z_{\alpha}$.

> - Right-tailed test: Reject if z $\geq z_{\alpha}$.

> - Two-tailed test: Reject if z $\geq z_{\alpha}$ or z $\leq -z_{\alpha}$.


> STEP 5: State a conclusion.


---

**Exercise:** The magazine Tech Worx reported that 92% of software engineers rate the company they work for as "a great place to work." As a veteran headhunter, you claim the percentage given in the report is not correct. In a survey of 210 randomly chosen software engineers, 188 rated the company they work for as "a great place to work." Perform a hypothesis test to see if there is enough evidence, at the 0.10 level of significance, to support your claim that the proportion, p, of all software engineers who rate the company they work for as "a great place to work" is not 92%.

--

- Ho: p = 0.92 and $H_1:$ p $\neq$ 0.92

--

Checking assumptions: $np_o$ = (210)(0.92) = 193.2 > 10 and n(1 - $p_o$) = (210)(1 - 0.92) = 16.8 > 10

--

Compute the test statistic, Z = $\frac{\hat{p} - p_o}{\sqrt{\frac{p_o(1 - p_o)}{n}}}$


- Sample proportion, $\hat{p} = \frac{188}{210}$ = 0.895


- Z = $\frac{0.895 - 0.92}{\sqrt{\frac{0.92(1 - 0.92)}{210}}}$ = -1.323


---

**Using the P-value method for a two-tailed test.**


- Use ALEKS calculator to find the left-tailed area: P(Z < -1.323)


- Because of symmetry, the right-tailed area is the same. Therefore, the P-value = 2*P(Z < -1.323) = 0.186 


- Since the P-value > $\alpha$, we fail to reject Ho.


--

**Using the Critical Value method for a two-tailed test.**


- Since $\alpha$ = 0.10, the critical values are determined for tails areas of 5% each.


- Using ALEKS calculator find the right-tailed critical value: $Z_{0.05}$.


- $Z_{0.05}$ = 1.645


- Because of symmetry, the left-tailed critical value is its negative, -1.645.


- Since the test statistic, z = -1.323, is not in the rejection region, we fail to reject Ho.

---


Conclusion

- <p>There is not enough evidence to support the claim that the percentage of software engineers who rate the company they work for as "a great place to work" is not 92%.</p>


---

### Testing the Population Mean: Z test

--

Assumptions (when $\sigma$ is known):


- We have a simple random sample.


- The sample size is large (n > 30), **OR** the population is approximately normal.

--

Once these assumptions are met, a hypothesis test can be performed using the following steps:


*1)* State the null and alternate hypothesis.


*2)* Choose a significance level $\alpha$, and find the critical value or values.


*3)* Compute the test statistic, Z = $\frac{\bar{x} - \mu_o}{\sigma/\sqrt{n}}$


*4)* Determine whether to reject Ho if the test statistic (Z) is in the critical region.


---

**Exercise:** A company that manufactures batteries used in electric cars is reporting that their newest model of battery has a mean lifetime, $\mu$, of 18 years. To test the company's claim, a competitor has selected 64 of these batteries at random. The mean lifetime of the sample is 16.6 years. Suppose the population standard deviation of these lifetimes is known to be 4.7 years.

Is there enough evidence to reject the claim that the mean lifetime of the newest model is 18 years? Perform a hypothesis test, using the level of significance of 0.05.

--

- Ho: $\mu$ = 18


- $H_1$: $\mu \neq$ 18

--

- The population standard deviation, $\sigma$, is **KNOWN** and the sample size is large (generally n > 30) **OR** the population distribution is at least approximately normal.


- Z = $\frac{\bar{x} - \mu_0}{\frac{\sigma}{\sqrt{n}}}$


- Z = $\frac{16.6 - 18}{\frac{4.7}{\sqrt{64}}}$ = -2.383


---

The P-value approach


- In ALEKS calculator: 2*P(Z < -2.383)


- Because this is a two-tailed test, we multiply by two.


- P-value = 0.017


- Since the p-value is less than (or equal to) the level of significance, the null hypothesis is rejected. So, there is enough evidence to reject the claim that the mean lifetime of the newest model of battery is 18 years.


---

The rejection region approach *(Critical value method)*


- In ALEKS calculator: $Z_{0.025}$


- The output is 1.96 which is the Z critical value for the right tail. Since this is a two-tailed test, the other Z critical value is -1.96.


- Rejection region: $(\infty, -1.96)$ and $(1.96, \infty)$


- Since the test statistic, -2.383, is in the rejection region, reject Ho.

---



