---
title: "Review for Exam 4"
date: "May 5, 2025"
output:
  xaringan::moon_reader:
    css: "myCSS.css"
    self_contained: true
    chakra: "remark-latest.min.js"
    nature:
      countIncrementalSlides: false
---

### The Signed-Rank Test

--

The Wilcoxon's signed-rank test is a **nonparametric** test designed to determine whether population **medians** differ when the data are in the form of **paired** samples. *(Ho: Same medians)*

--

It is therefore a nonparametric alternative to the t-test for matched pairs.

--

The main advantage of this nonparametric test is that it does not require that the population of differences have a specified distribution such as the normal distribution.

--

However, it does require that the distribution be approximately **symmetric**.


---


The following table contains the first exam score and the second exam score for a random sample of 12 students in a large college class.

Exam 1 | 76.5 | 88.5 | 79.5 | 84.5 | 86.5 | 80.5 | 76 | 79 | 75 | 77.5 | 78 | 85.5
:----|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:
Exam 2 | 72.5 | 98 | 83.5 | 91.5 | 76.5 | 75.5 | 69 | 84.5 | 75 | 70.5 | 78 | 89.5
Diff | 4 | -9.5 | -4 | -7 | 10 | 5 | 7 | -5.5 | 0 | 7 | 0 | -4

At the 0.02 level of significance, can we conclude (by using the Wilcoxon signed-rank test) that there is a difference between the populations of first and second exam scores for students in this class?

*a)* Find the value of the test statistic.

--

- Ho: The population median of first and second exam scores are identical.

--

- $H_1$: The population median are NOT identical.


---


- After computing the difference, given in table, find their absolute values.


- |d| = 4, 9.5, 4, 7, 10, 5, 7, 5.5, 0, 7, 0, 4

--

- Rank the absolute values, but ignore any zero.


- Sorting: 4, 4, 4, 5, 5.5, 7, 7, 7, 9.5, 10

- Ranking: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

--

Some considerations:


- Since the zeroes are ignored, ten numbers are ranked.


- The numbers 4 are rank in 1, 2, 3 places, but we take the rank "average", 2. Similarly, the number 7 is rank 7, average of ranks 6, 7, and 8.


---

Next step, assign the sign of the difference to the corresponding rank.


Exam 1 | 76.5 | 88.5 | 79.5 | 84.5 | 86.5 | 80.5 | 76 | 79 | 75 | 77.5 | 78 | 85.5
:----|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:
Exam 2 | 72.5 | 98 | 83.5 | 91.5 | 76.5 | 75.5 | 69 | 84.5 | 75 | 70.5 | 78 | 89.5
Diff | 4 | -9.5 | -4 | -7 | 10 | 5 | 7 | -5.5 | 0 | 7 | 0 | -4
Abs Value | 4 | 9.5 | 4 | 7 | 10 | 5 | 7 | 5.5 | 0 | 7 | 0 | 4
Rank | 2 | 9 | 2 | 7 | 10 | 4 | 7 | 5 | - | 7 | - | 2
Signed | 2 | -9 | -2 | -7 | 10 | 4 | 7 | -5 | - | 7 | - | -2 

--

Add the absolute values of the negative signed ranks: 9 + 2 + 7 + 5 + 2 = 25

Add the positive ranks: 2 + 10 + 4 + 7 + 7 = 30

--

For a **two-tailed test**, the test statistic value, T, is the SMALLER of the two sums.


- Test statistic, **T = 25**.

---


*b)* Find the critical value.

--

- Use the Critical Values for the Wilcoxon Signed-Ranks Test table in ALEKS.


- The **n** is the number of nonzero differences, 10.


- Using the table for n = 10, $\alpha$ = 0.02 and two-tailed test, the critical value is **5**.

--

*c)*  Decide whether to reject Ho.

--

- Reject Ho when the test statistic is LESS THAN critical value.


- There is not enough evidence to suggest that the population exam scores are different. 


---

The human resources department of a large investment bank announced that the number of people it interviews monthly has a mean of 100 with a standard deviation of 16.3. The management of the bank suspects that the standard deviation exceeds 16.3. Suppose that the management wants to take a small sample of months and carry out a hypothesis test to see if its suspicions have support. State the null hypothesis Ho and the alternative hypothesis $H_1$ that it would use for this test. 

--

- Ho: $\sigma$ = 16.3

--

- $H_1$: $\sigma$ > 16.3


---


A psychologist wants to test whether there is any difference in puzzle-solving abilities between boys and girls. Independent samples of thirteen boys and nine girls were chosen at random. The boys took a mean of 36 minutes to solve a certain puzzle, with a standard deviation of 5.5 minutes. The girls took a mean of 37 minutes to solve the same puzzle, with a standard deviation of 5.3 minutes. Assume that the two populations of completion times are normally distributed, and that the population variances are equal. Can we conclude, at the 0.05 level of significance, that the mean puzzle-solving times for boys, $\mu_1$ differs from the mean puzzle-solving times for girls, $\mu_2$? $\phantom{ALEKS, OBJ7}$


*a)* State the null hypothesis, Ho and the alternative hypothesis, $H_1$.

--

- Setting the sub index 1 for boys and 2 for girls


- Ho: $\mu_1 - \mu_2$ = 0


- $H_1: \mu_1 - \mu_2 \neq$ 0

---


*b)* Determine the type of test statistic to use.

--

- T-test


- Degrees of freedom = 13 + 9 - 2 = 20

--

*c)* Find the value of the test statistic. 

--

- Since the population variances are assumed to be equal, we are going to pooled the standard deviation.


- t = $\frac{(\bar{X}_1 - \bar{X}_2) - (\mu_1 - \mu_2)}{S_p\sqrt{\frac{1}{n_1} + \frac{1}{n_2}}}$


- $S_p$ is the pooled standard deviation: $\sqrt{\frac{(n_1 - 1)S_1^2 + (n_2 - 1)S_2^2}{(n_1 + n_2 - 2)}}$


- $S_p = \sqrt{\frac{(12)(5.5^2) + (8)(5.3^2)}{13 + 9 -2}}$ = 5.421


- t = $\frac{(36 - 37) - 0}{5.421\sqrt{1/13 + 1/9}}$ = -0.425

---


*d)* Find the p-value.

--

- Since this is a TWO-TAILED test, the p-value corresponds to the area below -0.425 and above 0.425.


- IN ALEKS *(area above 0.425)*: P(t > 0.425 with df=20)

--

- Right-tailed area is 0.3377

--

- By symmetry, the area below -0.425 is the same 0.3377

--

- The p-value is 0.3377 + 0.3377 = 0.6754

--

*e)* Can we conclude that the mean puzzle-solving times for boys differs from the mean puzzle-solving times for girls? Explain.

--

- Compare the p-value and alpha. Since alpha = 0.05, p-value > alpha.

--

- There is NOT enough evidence to conclude that the mean puzzle-solving times for boys differs from the mean puzzle-solving times for girls


---

According to a high-profile realtor, houses in the sleepy town of Sun Beach have shown higher appreciation over the past three years than have houses in the bustling town of North Arden. To test the realtor's claim, an economist has found fourteen recently sold homes in Sun Beach and fourteen recently sold homes in North Arden that were owned for exactly three years. The following table gives the appreciation (expressed as a percentage increase) for each of the twenty-eight houses.

Sun Beach: 12.1, 7.8, 14.3, 8.0, 9.3, 9.9, 9.0, 13.9, 8.4, 12.1, 10.4, 11.9, 10.9, 13.3

North Arden: 9.3, 11.0, 9.1, 8.6, 6.4, 6.4, 10.1, 8.3, 10.8, 10.8, 10.2, 6.5, 9.3, 9.9

Assume that the two populations of appreciation rates are normally distributed and that the population variances are equal. Can we conclude, at the 0.05 level of significance, that the mean appreciation rate of houses in Sun Beach, $\mu_1$, is higher than $\mu_2$, the mean appreciation rate of houses in North Arden? 


**Finding the solution in R**

---

> Data > New Data Set > Enter name for data set: **houses**

> Click **Add row** 28 times. Next, click **Add column** one time

> Change the name **V1** to **rate**. Then, enter the Sun Beach data values followed by the North Arden ones.

> Change the name **V2** to **place**. Next, enter the number "1" to the first fourteen rows and the number "2" for the last fourteen rows. > OK

> Data > Manage variables in active data set > Convert numeric variables to factor > Variables: **place** > OK > Yes

> Type **Sun Beach** in 1 and **North Arden** in 2.

> Statistics > Means > Independent samples t-test

> Groups: **place** and Response Variable: **rate**

> OPTIONS > Choose " Difference > 0" and Assume equal variance? "Yes" > OK


---

```{r comment=NA, echo=F}

# Copy data

x <- c(12.1, 7.8, 14.3, 8.0, 9.3, 9.9, 9.0, 13.9, 8.4, 12.1, 10.4, 11.9, 10.9, 13.3)

y <- c(9.3, 11.0, 9.1, 8.6, 6.4, 6.4, 10.1, 8.3, 10.8, 10.8, 10.2, 6.5, 9.3, 9.9)

t.test(x, y, mu = 0, alternative = "greater", var.equal = T)


```

*a)* State the null hypothesis Ho and the alternative hypothesis $H_1$

- Ho: The true difference in means is equal to 0

- $H_1$: The true difference in means is greater than 0


*b)* Determine the type of test statistic to use.

- This is a t-test

---

*c)* Find the value of the test statistic.

- t = 2.4158

*d)* Find the p-value. 

- 0.01151

*e)* Can we conclude that the mean appreciation rate of houses in Sun Beach, $\mu_1$, is higher than $\mu_2$, the mean appreciation rate of houses in North Arden?

- Since p-value > 0.05, reject Ho.



---


At a nearby college, there is a school-sponsored website that matches people looking for roommates. According to the school's report, 43% of students will find a match their first time using the site. A writer for the school newspaper tests this claim by choosing a random sample of 160 students who visited the site looking for a roommate. Of the students surveyed, 54 said they found a match their first time using the site.


Complete the parts below to perform a hypothesis test to see if there is enough evidence, at the 0.05 level of significance, to reject the claim that the proportion, p, of all students who will find a match their first time using the site is 43%.

*a)*  State the null hypothesis (Ho) and the alternative hypothesis $(H_1)$ that you would use for the test.

--

- Ho: p = 0.43


- $H_1$: p $\neq$ 0.43


---

*b)* For your hypothesis test, you will use a Z-test. Find the values of np and n(1 - p) to confirm that a Z-test can be used. Here, n is the sample size and p is the population proportion that you are testing.

--

- n = 160, p = 0.43


- np = (160)(0.43) = 68.8


- n(1 - p) = (160)(1 - 0.43) = 91.2


- Since 68.8 and 91.2 are more than 10, the Z-test is appropriate.

--

*c)* Perform a Z-test and find the P-value.

--

- Z = $\frac{\hat{p} - p}{\sqrt{\frac{p(1 - p)}{n}}}$ = $\frac{0.3375 - 0.43}{\sqrt{\frac{0.43(1 - 0.43)}{160}}}$ = -2.3634


- Since this is a two-tailed test, we find the area below the Z-test -2.3634 and multiply by 2.


- P-value = 2*P(Z $\leq$ -2.3634) = 2(0.009) = 0.018


---

*d)* Based on your answer to part (c), what can be concluded, at the 0.05 level of significance, about the claim made in the school's report?

--

- Since the P-value $\leq$ 0.05, reject Ho.


- There is enough evidence to reject the claim that 43% of students will find a match their first time using the site.


---







